#!/bin/bash

export USE_OPENSDK=yes

export XTENSA_TOOLS_ROOT=<path_to>/esp-open-sdk/xtensa-lx106-elf/bin/

export PATH=$XTENSA_TOOLS_ROOT:$PATH
export SDK_BASE=<path_to>/esp-open-sdk/ESP8266_NONOS_SDK-2.1.0-18-g61248df
export ESPTOOL=<path_to>/esp-open-sdk/esptool/esptool.py
export ESPPORT=/dev/ttyUSB0
export ESPBAUD=460800

